spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yumyum?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: zhsl106

logging:
  level:
    root: INFO
    com.dietcoach.project: DEBUG

elevenst:
  api:
    key: c79b603aecf72f9c74f74279df8dc0da
    base-url: http://openapi.11st.co.kr/openapi/OpenApiService.tmall

gms:
  openai:
    base-url: https://gms.ssafy.io/gmsapi
    api-key: S14P02CE06-255ba570-2c59-48eb-a2ed-e34bac45bdd6
    timeout-ms: 3600000

jwt:
  secret: 0123456789abcdef0123456789abcdef0123456789abcdef
  access-token-validity-in-seconds: 86400
  refresh-token-validity-in-seconds: 604800
